src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{

    const TVA = 1.1; 

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column()]
    private ?float $priceHT = null;

    #[ORM\Column()]
    private ?float $PriceTTC = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255,nullable: true)]
    private ?string $name = null;


    #[ORM\ManyToOne(inversedBy: 'factures')]
    private ?Client $client = null;

    #[ORM\OneToOne(mappedBy: 'facture', cascade: ['persist', 'remove'])]
    private ?Reservation $reservation = null;




    #[ORM\PrePersist]
    public function prePersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->priceHT = $this->PriceTTC / self::TVA;
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getPriceHT(): ?float
    {
        return $this->priceHT;
    }

    public function setPriceHT(float $priceHT): static
    {
        $this->priceHT = $priceHT;


        return $this;
    }

    public function getPriceTTC(): ?float
    {
        return $this->PriceTTC;
    }

    public function setPriceTTC(float $PriceTTC): static
    {
        $this->PriceTTC = $PriceTTC;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function __toString(): string
    {
        return (string)$this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(?Reservation $reservation): static
    {
        // unset the owning side of the relation if necessary
        if ($reservation === null && $this->reservation !== null) {
            $this->reservation->setFacture(null);
        }

        // set the owning side of the relation if necessary
        if ($reservation !== null && $reservation->getFacture() !== $this) {
            $reservation->setFacture($this);
        }

        $this->reservation = $reservation;

        return $this;
    }

}

templates/pdf/invoice_template.html.twig
<html lang="fr">
<head>
    <style>
       body {
  background: #ccc;
  padding: 30px;
  font-size: 0.6em;
}

h6{font-size:1em;}

.container {
  width: 21cm;
  min-height: 29.7cm;
}

.invoice {
  background: #fff;
  width: 100%;
  padding: 50px;
}

.logo {
  width: 4cm;
}

.document-type {
  text-align: right;
  color: #444;
}

.conditions {
  font-size: 0.7em;
  color: #666;
}

.bottom-page {
  font-size: 0.7em;
}
    </style>
 <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous" >

</head>
<body>
     

    <div class="container">
            <div class="invoice">
                <div class="row">
                    <div class="col-7">
                        <img src="https://ebtaxi91.fr/logo.jpg" class="logo"/>
                    </div>
                    <div class="col-5">
                        <h1 class="document-type display-4">FACTURE</h1>
                        <p class="text-right"><strong>#{{ reservation.facture.id }}</strong></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <p class="addressMySam">
                            <strong>TAXI EL BOUROUMI</strong><br/>
                            28 RUE DE L'EUROPE<br/>
                            91700 VILLIERS-SUR-ORGE
                            <br/>
                            Tel : (+33) 6.58.98.87.07
                        </p>
                    </div>
                    <div class="col-5">
                        <br/><br/><br/>
                        <p class="addressDriver">
                            <strong>{{ reservation.client.firstName }} {{ reservation.client.lastName }}</strong><br/>
                             <span>{{ reservation.client.phoneNumber }}</span>
                        </p>
                    </div>
                </div>
                <br/>
                <br/>
                <h6>Frais de services TAXI EL BOUROUMI le {{ reservation.reservationdatetime|date('d/m/Y') }}
                </h6>
                <br/>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Description</th>
                        <th>TVA</th>
                        <th class="text-right">Total HT</th>
                        <th class="text-right">Total TTC</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            Frais de transport : de {{ reservation.depAddress }}  à  {{ reservation.destination }}
                        </td>
                        <td>10%</td>
                        <td class="text-right" >{{ reservation.facture.priceHT|round('2','common') }}€</td>
                        <td class="text-right" >{{ reservation.facture.priceTTC}}€</td>
                    </tr>
                    
                   
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-8">
                    </div>
                    <div class="col-4">
                        <table class="table table-sm text-right">
                            <tr>
                                <td><strong>Total HT</strong></td>
                                <td class="text-right">{{ reservation.facture.priceHT|round(2,'common')}}€</td>
                            </tr>
                            <tr>
                                <td>TVA 10%</td>
                                <td class="text-right">{{(reservation.facture.priceTTC - reservation.facture.priceHT)|round('2','common')}}€</td>
                            </tr>
                            <tr>
                                <td><strong>Total TTC</strong></td>
                                <td class="text-right">{{ reservation.facture.priceTTC}}€</td>
                            </tr>
                        </table>
                    </div>
                </div>
    
                <br/>
                <br/>
                <br/>
                <br/>
    
                <p class="bottom-page text-right">
                    TAXI EL BOUROUMI - N° SIRET RCS Evry : 812 502 805 00029<br/>
                    28 RUE DE L'EUROPE 91700 VILLIERS-SUR-ORGE - www.ebtaxi91.fr/<br/>
                    N° TVA Intracom. FR83812502805<br/>
                </p>
            </div>
        </div>
</body>
</html>